### ISSUE TITLE
Error vue.runtime.esm.js:619 [Vue warn]: Invalid handler for event "focusout": got undefined

### ISSUE THREAD

**Issue by MDornian** [mattzollinhofer/vue-typeahead-bootstrap#61] opened 2020-07-08 00:30 UTC
When I upgraded to 2.4.0 I received the following error:

```
vue.runtime.esm.js:619 [Vue warn]: Invalid handler for event "focusout": got undefined

found in

---> <VueTypeaheadBootstrap> at node_modules/vue-typeahead-bootstrap/src/components/VueTypeaheadBootstrap.vue
       <BNavbar>
         <App> at src/App.vue
           <Root>
```

I worked around the problem by going back to version 2.1.2.

**Comment by mattzollinhofer** [comment] 2020-07-08 01:15
Hmm, can you provide any more detail for reproduction? Is it when you do something in particular?

**Comment by MDornian** [comment] 2020-07-08 03:31
I will have to create a small example project.  Hopefully on Friday.

**Comment by MDornian** [comment] 2020-07-09 19:50
Ok, I built a simple application to demonstrate the problem except that the problem didn't appear.  I went back to my main project and deleted `package-lock.json` and the `node-modules` directory and re-installed. Now the problem has disappeared in the main project.  

Feel free to close the issue.  Sorry, I don't know the etiquette of who closes the problem.

**Comment by mattzollinhofer** [comment] 2020-07-10 03:27
No worries, glad it wasn’t an issue.  

You’re welcome to close it, but I will since I’m here 😀

**Closed by mattzollinhofer** 2020-07-10 03:27 UTC
Labels: question
